# Generated by Django 5.2 on 2025-04-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='Número da CNH')),
                ('validade_cnh', models.DateField(verbose_name='Validade da CNH')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Marca')),
                ('pais_origem', models.CharField(max_length=50, verbose_name='País de Origem')),
                ('fundacao', models.DateField(verbose_name='Ano de Fundação')),
                ('website', models.URLField(verbose_name='Site Oficial')),
                ('ativa', models.BooleanField(default=True, verbose_name='Marca Ativa?')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tipo', models.CharField(choices=[('CAR', 'Carro'), ('MOT', 'Motocicleta'), ('CAM', 'Caminhão'), ('VAN', 'Van')], max_length=3, verbose_name='Tipo de Veículo')),
                ('ano_fabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='rental.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de Veículo',
                'verbose_name_plural': 'Modelos de Veículos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Frota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('km_atual', models.PositiveIntegerField(default=0, verbose_name='Quilometragem Atual')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível?')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_frota', to='rental.veiculo')),
            ],
            options={
                'verbose_name': 'Unidade da Frota',
                'verbose_name_plural': 'Frota de Veículos',
                'ordering': ['veiculo__marca', 'veiculo__modelo'],
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alocacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Alocação')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('km_inicial', models.PositiveIntegerField(help_text='Quilometragem no momento da alocação', verbose_name='Quilometragem Inicial')),
                ('km_final', models.PositiveIntegerField(blank=True, help_text='Quilometragem no momento da devolução', null=True, verbose_name='Quilometragem Final')),
                ('motivo', models.TextField(max_length=500, verbose_name='Motivo da Alocação')),
                ('observacoes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='rental.cliente', verbose_name='Cliente')),
                ('unidade_frota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='rental.frota', verbose_name='Unidade da Frota')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='rental.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
                'ordering': ['-data_alocacao'],
                'indexes': [models.Index(fields=['-data_alocacao'], name='rental_aloc_data_al_04bb7d_idx'), models.Index(fields=['unidade_frota', 'data_devolucao'], name='rental_aloc_unidade_a49976_idx')],
            },
        ),
    ]
