# Generated by Django 5.2 on 2025-05-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='km_estimado',
            field=models.PositiveIntegerField(blank=True, help_text='Estimativa de quilômetros a serem rodados', null=True, verbose_name='Quilômetros a Rodar'),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='data_alocacao',
            field=models.DateTimeField(verbose_name='Data de Alocação'),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='km_final',
            field=models.PositiveIntegerField(blank=True, help_text='Quilômetros efetivamente rodados', null=True, verbose_name='Quilômetros Rodados'),
        ),
    ]
